modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="custommobsforge_common"
version="1.0.0"
displayName="Custom Mobs Forge Common"
description="Common code for Custom Mobs Forge."