modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"
issueTrackerURL="https://github.com/yourusername/yourmod/issues"

[[mods]]
modId="custommobsforge"
version="1.0.0"
displayName="Custom Mobs Forge"
description="A mod that adds custom mobs to Minecraft."
authors="Your Name"