modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="custommobsforge_server"
version="1.0.0"
displayName="Custom Mobs Forge Server"
description="Server-side mod for Custom Mobs Forge."

[[dependencies.custommobsforge_server]]
modId="custommobsforge_common"
mandatory=true
versionRange="[1.0.0,)"
ordering="NONE"
side="BOTH"