modLoader="javafml"
loaderVersion="[47,)"
license="ALL Rights Reserved"
issueTrackerURL="https://example.com/issues"

[[mods]]
modId="custommobsforge_server"
version="1.0.0"
displayName="Custom Mobs Forge Server"
description="Server module for Custom Mobs Forge."
authors="YourName"

[[dependencies.custommobsforge_server]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="SERVER"

[[dependencies.custommobsforge_server]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="SERVER"