modLoader="javafml"
loaderVersion="[47,)"
license="ALL Rights Reserved"
issueTrackerURL="https://example.com/issues"

[[mods]]
modId="custommobsforge_client"
version="1.0.0"
displayName="Custom Mobs Forge Client"
description="Client module for Custom Mobs Forge."
authors="YourName"

[[dependencies.custommobsforge_client]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="CLIENT"

[[dependencies.custommobsforge_client]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="CLIENT"

[[dependencies.custommobsforge_client]]
modId="geckolib"
mandatory=true
versionRange="[4.7.1.2,)"
ordering="NONE"
side="CLIENT"